### ISSUE TITLE
node.js compatibility

### ISSUE THREAD

**Issue by SimonSapin** [tabatkins/railroad-diagrams#10]
I’m working on a Python port of this, to use in [Bikeshed](https://github.com/tabatkins/bikeshed). I’d like to use node.js for testing (comparing the output of the two implementations), which currently fails because `window` is undefined.

It would be nice to use some kind of "universal module" pattern, but I don’t know which flavor to pick.

**Comment by jonathanKingston** [comment]
I would probably rewrite the code to be different modules and use a make file to build it into a single browser include. I would be tempted to use ECMA 6 techniques so the build script could be removed eventually (A browserify script could be provided as an alternative).

I know this ticket has been open a long time so I might be stating the obvious.

Anyway if I made the pull request would this approach be merged in?

**Comment by tabatkins** [comment]
How are you thinking of dividing it up?

**Comment by jonathanKingston** [comment]
I would probably have something similar to:
- railroad-diagram.js - compiled browser file
- package.json
- dist/
- lib/
  - SVG.js - this would contain fake SVG and real
  - Syntax.js - as the language methods
  - index.js - To be the interface of what then lib exposes
