### ISSUE TITLE
Fix Choice down spacing

### ISSUE THREAD

**Issue by robjhornby** [tabatkins/railroad-diagrams#106]
Nice library!

I noticed a problem in the Python package and have a fix for it (PR to follow). Here's a diagram which shows the problem:

```python
from railroad import Choice, Diagram, Group, Skip, Stack, Terminal

diagram = Diagram(
    Choice(
        0,
        Group(Choice(0, Skip(), Group(Stack(Terminal("abc"), Skip()), "inner")), "top"),
        Terminal("xyz"),
    )
)
```

With the current latest commit in this repo, it looks like:

<img width="642" alt="Screenshot 2024-01-03 at 23 52 59" src="https://github.com/tabatkins/railroad-diagrams/assets/8439319/853e7d95-0804-4c84-9667-b9eda759ec0e">

I think the `down` spacing of `Choice` is where the problem lies. After fixing it it looks like this:

<img width="642" alt="Screenshot 2024-01-03 at 23 53 22" src="https://github.com/tabatkins/railroad-diagrams/assets/8439319/22fcd94d-6062-4beb-86d8-a441043c98f9">

I'm not sure how to run the tests in this repo so I just got this working with the above example and haven't checked whether it breaks anything else.

**Comment by tabatkins** [comment]
Hm, looking at the code now, I'm pretty sure it's wronger than what #107 is fixing. I'll take a deeper look at this tomorrow.

**Comment by tabatkins** [comment]
And yup, the code was still making a lot of assumptions that predated the introduction of the "height" concept. All fixed now!

**Comment by robjhornby** [comment]
Thanks for the quick fix, looks good!
