### ISSUE TITLE
Add an expectation container

### ISSUE THREAD

**Issue by LHLaurini** [tabatkins/railroad-diagrams#112]
As an example, take the following diagram for a simplified C-like string:

    Diagram(
        "\"",
        ZeroOrMore(
            Choice(0,
                Sequence(
                    "\\",
                    Choice(1,
                        "n",
                        "\\",
                        "\""
                    )
                ),
                NonTerminal("any printable character")
            )
        ),
        "\""
    )

![image](https://github.com/tabatkins/railroad-diagrams/assets/8211726/5c1fcf7f-82c8-4408-a5ac-22e4ff1a7bca)

Suppose the input is `"\p"`, and that choices should be matched in order, from top to bottom:

- `"` matches: ok
- Try first branch:
  - `\` matches: ok
  - `p` does not match

In this case, it is unclear whether a parser should backtrack and try the second branch (`any printable character`)  or throw an error.

I believe an "expectation" container, where all items **must** match and no backtracking is allowed, would be useful.

**Comment by LHLaurini** [comment]
I suggest something like this:
![image](https://github.com/tabatkins/railroad-diagrams/assets/8211726/63445661-6887-48dd-99ca-e3408e5989fc)

I'm willing to work on it myself, as long as I have everyone's approval.

EDIT: an alternative using the current set of components:
![image](https://github.com/tabatkins/railroad-diagrams/assets/8211726/c5a5cdd5-896c-4978-a243-30b691afba4c)

**Comment by tabatkins** [comment]
Hm, is that sort of iconography reasonably well established elsewhere?

Happy to add something for this (it's very easy to add containers like that), just want to make sure it's doing something recognizable first.

**Comment by LHLaurini** [comment]
After searching for a while, I'm unable to find something similar on other diagrams. The closest I found is [Boost 
Sprit's expectation operator](https://www.boost.org/doc/libs/1_84_0/libs/spirit/doc/html/spirit/qi/reference/operator/expect.html).

As there doesn't seem to be any relevant standard, perhaps this would be best indicated by a comment instead of a new container?

I'm closing this for now until an existing example is found.
