### ISSUE TITLE
Doc confusion with branching logic

### ISSUE THREAD

**Issue by sukima** [tabatkins/railroad-diagrams#31]
My sincere apologies if this isn't an actual issue. I can not figure out how to accomplish the following branching logic based on the documentation provided in the README:

```
|-Promise--then-----------------|
         \     \             /
          \     throw---catch
           \__________/
```

Any help appreciated.

**Comment by tabatkins** [comment]
You can't do that sort of thing with this library; it only allows properly nested paths.  This does mean there can be duplication on some of the lines.
