### ISSUE TITLE
Mixed Sequences and non-Sequences in a Choice are not aligned

### ISSUE THREAD

**Issue by kalgon** [tabatkins/railroad-diagrams#32]
In the following diagram, choice 1 & 2 are aligned while 3 is not.

```javascript
Diagram.INTERNAL_ALIGNMENT = 'left';
Diagram(
  Choice(0,
    Terminal('choice 1'),
    Terminal('choice 2'),
    Sequence(
      Terminal('choice 3'),
      Terminal('and more')
    )
  )
)
```

Same problem with right alignment.

Maybe Sequence should not add leading and trailing paths (but only between 2 consecutive elements in a Sequence).

**Comment by tabatkins** [comment]
Ooh, thanks for the report. I'll look into this in the next week or two and see what I can do.
