### ISSUE TITLE
Can't make .svg file

### ISSUE THREAD

**Issue by WalkerCodeRanger** [tabatkins/railroad-diagrams#35]
I wanted to take the generated svgs and place them in .svg files.  Putting the XML in a file an referencing it from the browser just causes a broken image icon.  Additionally, trying to open the .svg file with [InkScape](https://inkscape.org/en/) (an open source svg editor), does open it, but everything is black and messed up.  I tried comparing the generated svgs to svgs saved by InkScape and other examples I found online.  It was missing an xml declaration like `<?xml version="1.0" encoding="UTF-8"?>` but that didn't fix the problem.  Adding `version="1.0" xmlns="http://www.w3.org/2000/svg"` attributes to the `<svg>` element made the browser render them the same messed up thing as InkScape did.

Seems like there is something not quite compliant about the generated svg, but I don't know svg well enough to say what it is.

**Comment by tabatkins** [comment]
Hmm, I think I'm generating them with the intention that they're directly embedded in HTML. To display independently, they need the `xmlns` attribute, but nothing else.

If you're getting messed-up black display, that sounds like the `<style>` isn't being applied.

**Comment by tabatkins** [comment]
Ah, yeah, now I remember: you have to include the .css file from this repo (or something similar) to display them properly.
