### ISSUE TITLE
feature suggestion: allow setting title for Terminal and NonTerminal

### ISSUE THREAD

**Issue by larshp** [tabatkins/railroad-diagrams#39]
Allow setting SVG title([ref](https://developer.mozilla.org/en/docs/Web/SVG/Element/title)) for Terminal and NonTerminal elements. This would show the title as a tooltip for the elements.

eg.
Terminal(text, href, title)
where title is optional

**Comment by tabatkins** [comment]
Sounds reasonable. Happy to review a PR, or I'll get to it at some point.

**Comment by tabatkins** [comment]
Committed in e9b1a12
