### ISSUE TITLE
OptionalSequence.Width bug

### ISSUE THREAD

**Issue by Vasek-gh** [tabatkins/railroad-diagrams#41]
**Commit**: _aaa704d_

**Test code:**
Diagram(
	OptionalSequence(
		NonTerminal('TestBlock1'),
		NonTerminal('TestBlock2')
	)
).addTo();

**Result:**
![default](https://cloud.githubusercontent.com/assets/13292613/21081866/c965ee04-bfe0-11e6-96a3-689a31ae2898.png)

**Possible solution:**
 File: _railroad-diagrams.js_ line: _382_
Change `this.width = Diagram.ARC_RADIUS*4;` to `this.width = Diagram.ARC_RADIUS*2;`

**Comment by tabatkins** [comment]
Ahhh, it looks like I never tested this with only one or two values. It works fine for 3+. ^_^

I'll have to do something a little more complicated to fix.

**Comment by tabatkins** [comment]
Okay, looks like it's all fixed now.  My code was just flat-out wrong and only worked specifically for 3 children, so I had to rewrite it from scratch. (And found some bugs in my Stack code, too, yay!)
