### ISSUE TITLE
sometime links not working

### ISSUE THREAD

**Issue by gbrault** [tabatkins/railroad-diagrams#42]
I did some research and this comes from the fact Stack "returns" hide some underlying nodes.
Correction I made into the Stack.prototype.format, where I add path bit by bits instead of the full "return".
I changed
```
Path(x, y)
	.arc('ne').down(Math.max(0, item.down + Diagram.VERTICAL_SEPARATION - Diagram.ARC_RADIUS*2))
	.arc('es').left(innerWidth)
	.arc('nw').down(Math.max(0, this.items[i+1].up + Diagram.VERTICAL_SEPARATION - Diagram.ARC_RADIUS*2))
	.arc('ws').addTo(this);
```

With

```javascript
var temp =y;
Path(x, y).arc('ne').down(Math.max(0, item.down + Diagram.VERTICAL_SEPARATION - Diagram.ARC_RADIUS*2)).addTo(this);
y+=Diagram.ARC_RADIUS+Math.max(0, item.down + Diagram.VERTICAL_SEPARATION - Diagram.ARC_RADIUS*2); 
x+=Diagram.ARC_RADIUS;
Path(x, y).arc('es').left(innerWidth).addTo(this);
y+=Diagram.ARC_RADIUS;x=x-innerWidth-Diagram.ARC_RADIUS;;
Path(x, y).arc('nw').down(Math.max(0, this.items[i+1].up + Diagram.VERTICAL_SEPARATION - Diagram.ARC_RADIUS*2)).addTo(this);
y+=Diagram.ARC_RADIUS+Math.max(0, this.items[i+1].up + Diagram.VERTICAL_SEPARATION - Diagram.ARC_RADIUS*2);
x=x-Diagram.ARC_RADIUS;
Path(x, y).arc('ws').addTo(this);
y = temp + Math.max(item.down + Diagram.VERTICAL_SEPARATION, Diagram.ARC_RADIUS*2) + Math.max(this.items[i+1].up + Diagram.VERTICAL_SEPARATION, Diagram.ARC_RADIUS*2);

```

**Comment by tabatkins** [comment]
Sorry for the late review on this!

Can you explain what the original problem was that led you to make this change? I do this sort of single-connected-path all thruout the library without trouble, and I don't immediately see any problem with the older code.

**Comment by gbrault** [comment]
If I can remember, ... long time ago ... Depending upon diagrams, before I made this change, the layout was not that good and links didn't work-- I cannot state what was the problem accurately without making some research! I'll try to make that and let you know.

Thanks for your original work!

I made a 'fork' you can see it here https://github.com/gbrault/railroad-diagrams

**Comment by tabatkins** [comment]
Cool! Well, if you ever do recall what the problem was, let me know. ^_^ I'll go ahead and close this issue for now.

**Comment by gbrault** [comment]
Now, if I remember well, in some conditions, the link (you can click on items) were hidden by the connection edge... But I should go deeper if you want more details...
I experienced that on some complexe grammars (in the sqlite example)
