### ISSUE TITLE
PYPI for python library

### ISSUE THREAD

**Issue by DancingQuanta** [tabatkins/railroad-diagrams#48]
Would be very nice if the python library could be put on Python Package Index (PYPI) for usual method of downloading modules and including in other applications.

**Comment by tabatkins** [comment]
Now that I know how to upload to pypi and have a nice release script (cribbed from my other projects), it's up on Pypi! Woo!

<https://pypi.org/project/railroad-diagrams/>

(Install with `pip install railroad-diagrams`, use with `import railroad`.)
