### ISSUE TITLE
Extend to use as process flow

### ISSUE THREAD

**Issue by eduo** [tabatkins/railroad-diagrams#49]
Are you aware of work to extend this library into a simple workflow diagram generator?

I've always liked railroad diagrams for their cleannes and would love to use them as a basis for simple flowchart-type process maps.

The only problem is that railroad diagrams have a couple of assumptions and clash with diagram flows:

- They assume you'll always reach a single end rather than having multiple outcomes
- They don't contemplate going "back"

Of the two the second poses a visual challenge, and probably would require being able to optionally reference individual sections to be able to point to them from other points.

Other limitations are more aesthetic (diferentiating a decision point visually, for example). And other requirements from a workflow are already covered (repetition, selection, etc.)

**Comment by tabatkins** [comment]
No work that I know of, no, and doing so would be a substantial complication/rewrite - the linear nature of the diagram means I could make a lot of assumptions in putting things together that would break with a more arbitrary flow.  I've definitely had people *ask* about this before, but it's not something I'm willing to do myself. The library as it stands does what I need it to do. ^_^

**Comment by eduo** [comment]
I understand.

I've been loking for a while for a way to horizontally reflect workflows and Railroad diagrams are so space efficient (because they flow in the same direction as text) I thought they'd work nicely.

I've been able to "sort of" make it work for simple workflows (see attached) but obviously they still miss some things and will never allow for complex interactions.

![screenshot 2017-09-29 12 35 20](https://user-images.githubusercontent.com/154630/31012638-c4f3e548-a512-11e7-9fa7-8c0f21483f4d.png)

I still believe they could be a solid foundation for a simplified and space-efficient workflow layout.

I'll see if I can [tweak](https://mermaidjs.github.io/mermaid-live-editor/#/view/Z3JhcGggTFIKQSgoICkpLS0-Q1tOZXddCkMtLT5EKEFzc2lnbikKSS0tPkwoUmUtQXNzaWduKQpMLS0-QwpELS0-SVtPcGVuXQpJLS0-RyhNYXJrIENvbXBsZXRlZCkKRy0tPkhbQ29tcGxldGVkXQpILS0-S1tDbG9zZWRdCkktLT4gSwpJLS0-SApGLS0-SQpJLS0-RihGb2xsb3dzLVVwKQo) Mermaid's [horizontal workflow layout](https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggTFIKQSgoICkpLS0-Q1tOZXddCkMtLT5EKEFzc2lnbikKSS0tPkwoUmUtQXNzaWduKQpMLS0-QwpELS0-SVtPcGVuXQpJLS0-RyhNYXJrIENvbXBsZXRlZCkKRy0tPkhbQ29tcGxldGVkXQpILS0-S1tDbG9zZWRdCkktLT4gSwpJLS0-SApGLS0-SQpJLS0-RihGb2xsb3dzLVVwKQo) but I won't hold my breath. I assume this is undoable or it would've been done by now :D

(the diagram only shows the main actions -rounded boxes- and states -straight boxes- for a simple ticketing system, direction, decision points and owners are obviated, as I want to use it to show where a worfklow in a detail view and/or as a dashboard of workflows stationed in each state)

**Comment by tabatkins** [comment]
Definitely not *un*doable, just *more difficult* to do. ^_^
