### ISSUE TITLE
How can we visualize this type of logic?

### ISSUE THREAD

**Issue by arbego** [tabatkins/railroad-diagrams#51]
Hello,

how can we visualize this type of logic:

    (A & (C | D)) | (B & D)

It would look like this in railroad:
![capture](https://user-images.githubusercontent.com/2493251/36370067-e379c742-155d-11e8-8ef1-3a4a1d4aafe4.PNG)

**Comment by tabatkins** [comment]
In this library you need to draw them out separately, exactly like they show up in your grammar fragment:

```
Diagram(
  Choice(0,
    Sequence("A", Choice(0, "C", "D")),
    Sequence("B", "D")))
```

I don't have support for drawing out more arbitrary graphs and connections like in your drawing, and don't plan to - doing so would be a *major* architectural change, and would be massively more complex than what I'm willing to get into. ^_^
