### ISSUE TITLE
How to use options

### ISSUE THREAD

**Issue by eddiewebb** [tabatkins/railroad-diagrams#52]
I am not a JS dev by nature, and only understand basic functions.

How to actually pass options like DIAGRAM_CLASS?

```
Diagram(
Terminal("Default Job","FLOW-COM-JOB1-147"),
Terminal("App 1","FLOW-COM-APP1-147"),
options={DIAGRAM_CLASS:"foo"}
).addTo();
```
```
Diagram({items:[
Terminal("Default Job","FLOW-COM-JOB1-147"),
Terminal("App 1","FLOW-COM-APP1-147")
],

options:[DIAGRAM_CLASS:"foo"]
).addTo();
```

**Comment by tabatkins** [comment]
Set them directly on the Diagram object:

```
Diagram.DIAGRAM_CLASS = "foo";
Diagram(...).addTo();
```

(This isn't very good API design, I know, but it was quick and easy. ^_^

**Comment by eddiewebb** [comment]
Thanks!  

DIAGRAM_CLASS replaces existing class, but is added as a string, so below will leave default CSS and add additional class for minor tweaks.

```
Diagram.DIAGRAM_CLASS = "railroad-diagram foo";
Diagram(...).addTo();
```
