### ISSUE TITLE
Feature Suggestion: Add an optional 'label' for each railroad diagram as on the JSON site

### ISSUE THREAD

**Issue by jleffler** [tabatkins/railroad-diagrams#55]
Each of the railroad diagrams on http://json.org/ has a 'label' or 'title' above the start of the railroad diagram.  For example, the first railroad diagram is labelled 'object'.

Please either document how to add those labels to the diagram or (preferably) provide a way to specify the diagram's label, maybe as an optional extra parameter to the `Diagram` function.

**Comment by tabatkins** [comment]
Done! You can manually construct a Start() and pass a label as the second argument, then give it as the first child of a Diagram().
