### ISSUE TITLE
Support a horizontal choice

### ISSUE THREAD

**Issue by matthijsgroen** [tabatkins/railroad-diagrams#59]
( I will try to create a PR for this myself later)

Currently choices are always vertical, but if you have an EBNF that has a choice for all 'letters' (upcase and downcase) you get a really long vertical list of elements (52 of them)

If we support horizontal choices as well, you can mix horizontal and vertical choices and make this more into a grid.

![img_9813](https://user-images.githubusercontent.com/23627/47783373-cf285480-dd02-11e8-9d6c-8fec94a6c18a.jpg)

I was thinking about the following syntax:

```
HorizontalChoice(...children)
```

so without the first argument of what should be considered as the default path.

**Comment by tabatkins** [comment]
Yeah, I'd accept a PR for this.

**Comment by matthijsgroen** [comment]
@tabatkins The PR is ready 😃#60

**Comment by tabatkins** [comment]
Committed.
