### ISSUE TITLE
ComplexDiagrams are actually start symbols, no?

### ISSUE THREAD

**Issue by sol** [tabatkins/railroad-diagrams#64]
> Alternately, you can call ComplexDiagram(); it's identical to Diagram(), but has slightly different start/end shapes, same as what JSON.org does to distinguish between "leaf" types like number (ordinary Diagram()) and "container" types like Array (ComplexDiagram()).

I think on json.org the different start/end shapes indicate what are valid start symbols.  They are used for `value` too by now.

**Comment by tabatkins** [comment]
...huh. That's an interesting view of things, but I'm not sure it's right. Like, per `value`, `number` is a valid start symbol.

It's pretty unclear what exactly JSON.org means by the distinction.
