### ISSUE TITLE
F# Port

### ISSUE THREAD

**Issue by Marti2203** [tabatkins/railroad-diagrams#67]
Hello, I have made an F# port to the Python version of the library. I would like to make a PR to add it to this repo, so people can use this library in .Net and see how useful it would be. If I have time, I will rework it for WebSharper :D but that is not sure yet.
Have a nice day!

**Comment by tabatkins** [comment]
I'm happy to link to your F# port, but as I can't commit to maintaining it as I add new features, I would prefer not to put it directly in this repo.

If you've finished it and have it published, tho, let me know!

**Comment by Marti2203** [comment]
Hello! It is fully working. I do not think the API is very intuitive and I may have to rework it but I have to clear up uni so I have some free time to think it out. I am going to develop it, I just wanted to have it mentioned
