### ISSUE TITLE
No AlternatingSequence example in README

### ISSUE THREAD

**Issue by lurch** [tabatkins/railroad-diagrams#76]
While working on a recent PR, I noticed that there was an `AlternatingSequence` class, but there's no mention of this in the README file. Could you add an example with a matching screenshot please? :slightly_smiling_face:

**Comment by tabatkins** [comment]
Done, thanks for the ping. ^_^

(Also undocumented is Block, a leaf node, but that really just exists for testing purposes, so I can generate something of an arbitrary size.)
