### ISSUE TITLE
Add a container : Group()

### ISSUE THREAD

**Issue by YannisDelmas** [tabatkins/railroad-diagrams#77]
It would be great to add a new container, `Group(child, label)`, allowing to render Regular expression groups, as in the following diagram for the RegExp `/a(b)*c/`:
![image](https://user-images.githubusercontent.com/2866452/79496886-1b667200-8027-11ea-80b9-60f882d9c11f.png)

For diagrams not about regexps, it may be used to comment parts of the diagram.

It would be great that the label had the same width as the box, and that there both label and box had classes, for easy styling.

**Comment by tabatkins** [comment]
Yeah, I've seen this sort of thing in railroads before. Seems pretty reasonable, and wouldn't be difficult.

**Comment by tabatkins** [comment]
And done - check the README for documentation.
