### ISSUE TITLE
Options to colour the Terminals?

### ISSUE THREAD

**Issue by lurch** [tabatkins/railroad-diagrams#84]
I've got a pretty complicated "syntax grammar" made up of a whole bunch of railroad diagrams (25 of them!). I'm using the Python version of `railroad-diagrams` to generate all the diagrams in SVG format which I then display on an autogenerated HTML page.

Some of the "tokens" are keywords with no arguments, some of them are keywords which take a single numeric argument, some of them are keywords which take a single-word argument, and some of them are keywords which take a double-quoted string argument.
Currently, I differentiate between these different types with e.g.:
```
Terminal('high')
```

```
Sequence(Terminal('count'), NonTerminal('count_number'))
```

```
Sequence(Terminal('name'), NonTerminal('name_string'))
```

```
Sequence(Terminal('description'), NonTerminal('"description_string"'))
```

This all works fine, but I was wondering if it would be possible for the `NonTerminal` and `Terminal` objects to have an optional `background_colour=` parameter, so that I could give each of these different "types" of keywords / arguments a different background colour (rather than just the default light green), to make them easier to differentiate?

I didn't design this grammar, I "inherited" it on a big project, and I'm using railroad-diagrams to help me reverse-engineer the syntax and fully document it. Thanks for such a useful project :+1:

**Comment by tabatkins** [comment]
Good idea. I've implemented it by allowing you to pass additional classes to the Terminal, NonTerminal, and Comment constructors, so you can style them how you wish on an individual basis.  Version 1.1.0 has the fix.

**Comment by lurch** [comment]
Cool! I'll have a play on Monday :grinning:
