### ISSUE TITLE
Python port leaves gap after OptionalSequence

### ISSUE THREAD

**Issue by yengip** [tabatkins/railroad-diagrams#87]
Hi Tab,
Love the diagrams, thanks for porting to Python. 
There seems to be an anomaly when drawing OptionalSequence containers where there's a break in the main line which grows the more items you have in the sequence.

I have tried to find out why it's happening to see if I could fix it and contribute the fix, but the logic in the .format() method (where I think it might be happening) is beyond my capability to track I'm afraid.  I think the value of the x coordinate is getting out of step with the width of the items somewhere in there but I can't see through all the needsSpace, itemSpace, itemWidth and AR adjustments to work it out.

I don't know if you're still interested in this project but I thought I'd mention it to see if you can fix it or perhaps point me in the right direction.  It may be something in my environment I guess but I would have thought that would cause problems with the other containers, and I haven't seen any of that.

I've attached an image of the Chrome rendering python generated by:
Diagram(
  OptionalSequence(
  "Optional", "Optional",
  "Optional",
  ),
)

Plus, the svg code snipped from the html page and the same from the js generator web page.
[os_from_generator.txt](https://github.com/tabatkins/railroad-diagrams/files/6796262/os_from_generator.txt)
[os_from_python.txt](https://github.com/tabatkins/railroad-diagrams/files/6796263/os_from_python.txt)
![OptionalSequence python example](https://user-images.githubusercontent.com/86871336/125181123-8afee900-e1f9-11eb-9789-79b79dcaa410.jpg)

Cheers,
IP

**Comment by tabatkins** [comment]
Oooh, I expect something's not tracking the needsSpace stuff properly. Thanks for the report, I'll look into this in a bit.

**Comment by tabatkins** [comment]
Closed by #88
