### ISSUE TITLE
Bug in AlternatingSequence exception

### ISSUE THREAD

**Issue by ptmcg** [tabatkins/railroad-diagrams#90]
```
class AlternatingSequence(DiagramMultiContainer):
	def __new__(cls, *items):
		if len(items) == 2:
			return super(AlternatingSequence, cls).__new__(cls)
		else:
			raise Exception("AlternatingSequence takes exactly two arguments got " + len(items))

```
raises:

    TypeError: can only concatenate str (not "int") to str

Last line should use "str(len(items))" (or do proper format call:

    raise Exception("AlternatingSequence takes exactly two arguments got {0}".format(len(items)))

**Comment by tabatkins** [comment]
You're right, thanks for the report!
