### ISSUE TITLE
Give the dingus the ability to set the global options

### ISSUE THREAD

**Issue by govarney** [tabatkins/railroad-diagrams#92]
Currently each item in a "Choice" is always centered.  I'd like the option to left justify the items. Sometimes left justification makes the syntax easier to understand.  

Below is an example. The first image is generated by "railroad-diagrams" (with some additional coloring). The second is a photoshopped example of the same SVG with the "Choice" items left justified.

**Image 1**
![image](https://user-images.githubusercontent.com/20732442/149041747-860804a6-1b2c-4ccd-a78b-4bb99f1d6278.png)
**Image 2**
![image](https://user-images.githubusercontent.com/20732442/149042322-73b56f6f-a538-4158-9c9d-0a8a1c4e2ff1.png)

**Comment by tabatkins** [comment]
Is this something you want for an *individual* Choice, or for all the items in the diagram? Because the latter is already supported - one of the global options lets you toggle between justifying center/left/right whenever there's free space.

**Comment by govarney** [comment]
I thought the fact that it is centered might mean there already was a way to easily control justification, it's just that I don't know how, and opening an issue was the only way to ask. Hope you don't mind.

Given it's possible could you tell me how.  Thanks

**Comment by tabatkins** [comment]
All the global options are documented [in the README](https://github.com/tabatkins/railroad-diagrams#options); for Python they're [module-level globals](https://github.com/tabatkins/railroad-diagrams/blob/gh-pages/railroad.py#L9-L17), for JS they're [in the Options export](https://github.com/tabatkins/railroad-diagrams/blob/gh-pages/railroad.js#L21-L30)

**Comment by govarney** [comment]
Mmmm.  I'm just a user of the dingus. Not of your code.  I write the statements on the dingus page, get my diagram drawn for me, and then cut and paste the screen image.  Thanks anyway.

**Comment by tabatkins** [comment]
Oh, I see! Hm, I don't have the ability to control what comes out of the dingus yet. I can add that, def.

**Comment by tabatkins** [comment]
All right, as soon as gh-pages decides to update, the dingus will have all the relevant global options available for you to tweak! I don't yet track those in the URL, tho; I probably should.
