### ISSUE TITLE
[question]: text output?

### ISSUE THREAD

**Issue by bennypowers** [tabatkins/railroad-diagrams#94]
Hello!

I'm interested in the possibility of rendering railroad diagrams in text for use in neovim or other terminal-bound editors. Is that something that could be done with this library? Would it involve subclassing the various entities?

Cheers

**Comment by tabatkins** [comment]
I've thought about this before, too, and it's certainly *possible*, but it would involve essentially rewriting the entirety of the rendering functions. On the plus side, all the essential rendering logic has already been written once, so it should be relatively straightforward to translate over, but it's definitely a Task.

If you're interested in trying it out, you probably want the nice [box-drawing characters](https://tabatkins.github.io/symbols/)

**Comment by bennypowers** [comment]
Well I'm playing with the idea of using kitty image protocol in terminals to render the SVG graphics.

WDYT about a lua version of railroad-diagrams? That would ease integration with neovim (or any other lua host), regarding which I found this: https://gist.github.com/brimworks/1390733

**Comment by tabatkins** [comment]
I can't actively maintain a Lua version, so I'm not comfortable keeping such code in this repo, but I'm more than happy to link to a well-done port.

**Comment by RossPatterson** [comment]
FWIW, I built a railroad diagram text renderer for a mainframe-based tool ("B2H") about 20 years ago, in IBM's Rexx language.  The tool took IBM's BookMaster GML markup as input, so the syntax is different from this package's, but the data model is almost identical.  I have a need for text output myself, so I'm going to take a crack at re-writing my old work in Python as something like a set of `writeText()`  and `formatText()` methods for this package's classes.

**Comment by RossPatterson** [comment]
I have an implementation of text rendering for everything except OptionalSequence().  I'll be away for a few weeks, but I'll do that one when I'm back.  Other than that, it renders everything in `test.py` correctly, to my eyes at least.  I've attempted to make the Unicode box-drawing character version look as much like the SVG version as possible.  The pure-ASCII version, well, ain't know way that's gonna look that nice :-)

My changes do not affect any existing code - they are 100% new routines and a single new class.

Here are samples:

- [`test_svg.html`](https://rosspatterson.github.io/test_svg.html) - The SVG versions of all the test cases.
- [`test_unicode.html`](https://rosspatterson.github.io/test_unicode.html) - Same stuff, drawn in character-cell graphics, using the Unicode 25xx box-drawing characters.
- [`test_ascii.html`](https://rosspatterson.github.io/test_ascii.html) - Same stuff, drawn with pure ASCII characters.  This is the reason I'm doing the work, but it ain't pretty :-)

Feel free to comment on these results.  I'll be back online in a couple of weeks, and I'll get back to finishing this work.

**Comment by tabatkins** [comment]
Oh dang, that's neat! Having both renderers is nice - the box-drawing characters look real messed up given the fonts on my machine right now, but they look great in the console; the ASCII looks decent in both.

**Comment by RossPatterson** [comment]
> Having both renderers is nice 

It's actually just a single renderer, which takes a `dict` parameter that applies a character for each use.  And the renderer has a method to modify or wholly replace the dict.  So if, for example, you're using a font that has better rounded box corners, you can use them instead of the Unicode curved corners.

**Comment by RossPatterson** [comment]
Forgot to say - this is in Python right now.  If a PR is welcome for this work, I'll translate it to Javascript as well.

**Comment by tabatkins** [comment]
Definitely welcome. I'd also be happy to do the port myself, if you're more comfortable with Python. But if you're fine with JS as well, go ahead.

**Comment by RossPatterson** [comment]
I've implemented the last of the diagram classes, and updated the test result files (see above).  I'll start putting a PR together for the Python port.
