### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by jhpratt** [tabatkins/railroad-diagrams#98]
Would it be possible to maintain a changelog for this? My CI unexpectedly (and silently) broke because I forgot to pin the version, but it's impossible to me to actually upgrade to the latest version as I don't know what changed.

**Comment by tabatkins** [comment]
Yeah, I should. But let this be a lesson to always pin your dependencies to at *least* the major version; I correctly made this a major version bump *because* it was an API change that was very likely to break stuff. ^_^

**Comment by jhpratt** [comment]
Oh, of course! I have now. I just use Python so infrequently it wasn't something that immediately came to mind when I used this as part of documentation.

**Comment by tabatkins** [comment]
And written https://github.com/tabatkins/railroad-diagrams/issues/99
